export const ALL_OFFERS_REQUEST="ALL_OFFERS_REQUEST";
export const ALL_OFFERS_SUCCESS="ALL_OFFERS_SUCCESS";
export const ALL_OFFERS_FAIL="ALL_OFFERS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";